version: "3"

volumes:
      produtosdata:

networks:
      bridge:

services:

      mysql:
            image: "mysql:5.7"
            volumes:
                  - produtosdata:/var/lib/mysql
                  - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
            networks:
                  - bridge
            environment:
                  - MYSQL_ROOT_PASSWORD=numsey
                  - bind-adress=0.0.0.0

      mvc:
            build:
                  context: .
                  dockerfile: Dockerfile
            networks:
                  - bridge
            ports:
                  - 5000:80
            environment:
                  - DHOST=mysql
            depends_on:
                  - mysql